### ISSUE TITLE
Project breaks MIT license

### ISSUE THREAD

**Issue by BalintCsala** [sjrsjz/Dirt-RT#5]
This project uses various files from my project (https://github.com/BalintCsala/VulkaniteDemoPack), which is under the MIT license, which states: 

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

The easiest option to remedy this would be to put the original license into a "thirdparty" folder with a disclaimer at the bottom of the readme.

**Comment by sjrsjz** [comment]
updated thirdparty license

**Comment by BalintCsala** [comment]
awesome, thank you
